=== 2m4t/LiCShield/training_session/java_build/SPECjvm2008/resources/xml.validation/periodic_table.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="PERIODIC_TABLE">
    <xs:complexType>
      <xs:sequence>
	<xs:element maxOccurs="unbounded" ref="ATOM" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ATOM">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="NAME" />
	<xs:element ref="ATOMIC_WEIGHT" />
	<xs:element ref="ATOMIC_NUMBER" />
	<xs:element minOccurs="0" ref="OXIDATION_STATES" />
	<xs:element minOccurs="0" ref="BOILING_POINT" />
	<xs:element minOccurs="0" ref="MELTING_POINT" />
	<xs:element ref="SYMBOL" />
	<xs:element minOccurs="0" ref="DENSITY" />
	<xs:element ref="ELECTRON_CONFIGURATION" />
	<xs:element minOccurs="0" ref="COVALENT_RADIUS" />
	<xs:element minOccurs="0" ref="ELECTRONEGATIVITY" />
	<xs:element minOccurs="0" ref="ATOMIC_RADIUS" />
	<xs:element minOccurs="0" ref="HEAT_OF_VAPORIZATION" />
	<xs:element minOccurs="0" ref="ATOMIC_VOLUME" />
	<xs:element minOccurs="0" ref="HEAT_OF_FUSION" />
	<xs:element minOccurs="0" ref="IONIZATION_POTENTIAL" />
	<xs:element minOccurs="0" ref="SPECIFIC_HEAT_CAPACITY" />
	<xs:element minOccurs="0" ref="THERMAL_CONDUCTIVITY" />
      </xs:sequence>
      <xs:attribute name="STATE">
	<xs:simpleType>
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="GAS" />
	    <xs:enumeration value="SOLID" />
	  </xs:restriction>
	</xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="ATOMIC_NUMBER" type="xs:string" />
  <xs:element name="ATOMIC_RADIUS">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ATOMIC_VOLUME">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ATOMIC_WEIGHT" type="xs:string" />
  <xs:element name="BOILING_POINT">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="COVALENT_RADIUS">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="DENSITY">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ELECTRONEGATIVITY" type="xs:string" />
  <xs:element name="ELECTRON_CONFIGURATION" type="xs:string" />
  <xs:element name="HEAT_OF_FUSION">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="HEAT_OF_VAPORIZATION">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="IONIZATION_POTENTIAL" type="xs:string" />
  <xs:element name="MELTING_POINT">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="NAME" type="xs:string" />
  <xs:element name="OXIDATION_STATES" type="xs:string" />
  <xs:element name="SPECIFIC_HEAT_CAPACITY">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="SYMBOL" type="xs:string" />
  <xs:element name="THERMAL_CONDUCTIVITY">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:string">
	  <xs:attribute name="UNITS" type="xs:string" use="required" />
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 2m4t/LiCShield/training_session/java_build/SPECjvm2008/resources/xml.validation/periodicxsd.xml
<?xml version="1.0"?>

<PERIODIC_TABLE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation='periodic_table.xsd'>

  <ATOM>
    <NAME>Actinium</NAME>
    <ATOMIC_WEIGHT>227</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>89</ATOMIC_NUMBER>
    <OXIDATION_STATES>3</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">3470</BOILING_POINT>
    <SYMBOL>Ac</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      10.07
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Rn] 6d1 7s2 </ELECTRON_CONFIGURATION>
    <ELECTRONEGATIVITY>1.1</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.88</ATOMIC_RADIUS>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      22.5
    </ATOMIC_VOLUME>
    <IONIZATION_POTENTIAL>5.17</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      0.12
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      12
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Aluminum</NAME>
    <ATOMIC_WEIGHT>26.98154</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>13</ATOMIC_NUMBER>
    <OXIDATION_STATES>3</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">2740</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">933.5</MELTING_POINT>
    <SYMBOL>Al</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      2.7
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Ne] 3s2 p1 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">1.18</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>1.61</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.43</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      290.8
    </HEAT_OF_VAPORIZATION>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      10
    </ATOMIC_VOLUME>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      10.7
    </HEAT_OF_FUSION>
    <IONIZATION_POTENTIAL>5.986</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      0.9
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      237
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Americium</NAME>
    <ATOMIC_WEIGHT>243</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>95</ATOMIC_NUMBER>
    <OXIDATION_STATES>6, 5, 4, 3</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">2880</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">1449</MELTING_POINT>
    <SYMBOL>Am</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      13.7
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Rn] 5f7 7s2 </ELECTRON_CONFIGURATION>
    <ELECTRONEGATIVITY>1.3</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.84</ATOMIC_RADIUS>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      20.8
    </ATOMIC_VOLUME>
    <IONIZATION_POTENTIAL>6</IONIZATION_POTENTIAL>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      10
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Antimony</NAME>
    <ATOMIC_WEIGHT>121.757</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>51</ATOMIC_NUMBER>
    <OXIDATION_STATES>+/-3, 5</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">1860</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">903.91</MELTING_POINT>
    <SYMBOL>Sb</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      6.69
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Kr] 4d10 5s2 p3 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">1.4</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>2.05</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.59</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      67.97
    </HEAT_OF_VAPORIZATION>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      18.4
    </ATOMIC_VOLUME>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      19.83
    </HEAT_OF_FUSION>
    <IONIZATION_POTENTIAL>8.641</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      0.207
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      24.3
    </THERMAL_CONDUCTIVITY>
  </ATOM>
  
  <ATOM STATE="GAS">
    <NAME>Argon</NAME>
    <ATOMIC_WEIGHT>39.948</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>18</ATOMIC_NUMBER>
    <BOILING_POINT UNITS="Kelvin">87.45</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">83.95</MELTING_POINT>
    <SYMBOL>Ar</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      1.784
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Ne] 3s2 p6 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">0.98</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>0</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">0.88</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      6.506
    </HEAT_OF_VAPORIZATION>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      24.2
    </ATOMIC_VOLUME>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      1.188
    </HEAT_OF_FUSION>
    <IONIZATION_POTENTIAL>15.759</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      0.52
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      0.0177
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Arsenic</NAME>
    <ATOMIC_WEIGHT>74.9216</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>33</ATOMIC_NUMBER>
    <OXIDATION_STATES>+/-3, 5</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">876</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">1090</MELTING_POINT>
    <SYMBOL>As</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      5.78
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Ar] 3d10 4s2 p3 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">1.2</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>2.18</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.39</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      32.4
    </HEAT_OF_VAPORIZATION>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      13.1
    </ATOMIC_VOLUME>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      27.7
    </HEAT_OF_FUSION>
    <IONIZATION_POTENTIAL>9.81</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      0.33
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      50
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Astatine</NAME>
    <ATOMIC_WEIGHT>210</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>85</ATOMIC_NUMBER>
    <OXIDATION_STATES>+/-1, 3, 5, 7</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">610</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">575</MELTING_POINT>
    <SYMBOL>At</SYMBOL>
    <ELECTRON_CONFIGURATION>[Xe] 4f14 5d10 6s2 p5 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">1.47</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>2.2</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.45</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      30
    </HEAT_OF_VAPORIZATION>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      12
    </HEAT_OF_FUSION>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      1.7
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM STATE="SOLID">
    <NAME>Gold</NAME>
    <ATOMIC_WEIGHT>196.9665</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>79</ATOMIC_NUMBER>
    <OXIDATION_STATES>3, 1</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">3130</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">1337.58</MELTING_POINT>
    <SYMBOL>Au</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      19.3
    </DENSITY>
    <ELECTRON_CONFIGURATION>[Xe] 4f14 5d10 6s1 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">1.34</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>2.54</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">1.46</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      324.43
    </HEAT_OF_VAPORIZATION>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      10.2
    </ATOMIC_VOLUME>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      12.36
    </HEAT_OF_FUSION>
    <IONIZATION_POTENTIAL>9.225</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      0.128
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      317
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Boron</NAME>
    <ATOMIC_WEIGHT>10.811</ATOMIC_WEIGHT>
    <ATOMIC_NUMBER>5</ATOMIC_NUMBER>
    <OXIDATION_STATES>3</OXIDATION_STATES>
    <BOILING_POINT UNITS="Kelvin">4275</BOILING_POINT>
    <MELTING_POINT UNITS="Kelvin">2365</MELTING_POINT>
    <SYMBOL>B</SYMBOL>
    <DENSITY UNITS="grams/cubic centimeter"><!-- At 300K -->
      2.34
    </DENSITY>
    <ELECTRON_CONFIGURATION>1s2 2s2 p1 </ELECTRON_CONFIGURATION>
    <COVALENT_RADIUS UNITS="Angstroms">0.82</COVALENT_RADIUS>
    <ELECTRONEGATIVITY>2.04</ELECTRONEGATIVITY>
    <ATOMIC_RADIUS UNITS="Angstroms">0.98</ATOMIC_RADIUS>
    <HEAT_OF_VAPORIZATION UNITS="kilojoules/mole">
      507.8
    </HEAT_OF_VAPORIZATION>
    <ATOMIC_VOLUME UNITS="cubic centimeters/mole">
      4.6
    </ATOMIC_VOLUME>
    <HEAT_OF_FUSION UNITS="kilojoules/mole">
      22.6
    </HEAT_OF_FUSION>
    <IONIZATION_POTENTIAL>8.298</IONIZATION_POTENTIAL>
    <SPECIFIC_HEAT_CAPACITY UNITS="Joules/gram/degree Kelvin">
      1.026
    </SPECIFIC_HEAT_CAPACITY>
    <THERMAL_CONDUCTIVITY UNITS="Watts/meter/degree Kelvin">
    <!-- At 300K -->
      27
    </THERMAL_CONDUCTIVITY>
  </ATOM>

  <ATOM>
    <NAME>Barium</NAME>
    <ATOMIC_WEIGHT>137.33</ATOMIC_WEIGHT>
