=== 2m4t/LiCShield/training_session/java_build/SPECjvm2008/resources/xml.validation/structure.xsd
<?xml version="1.0"?>

<!--

file      : structure.xsd
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : Copyright (c) 2006 Code Synthesis Tools CC
license   : The structure.xml and structure.xsd files are part of the XSDBench W3C XML Schema
            benchmark: http://www.codesynthesis.com/projects/xsdbench/

-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:s="http://www.codesynthesis.com/xmlns/xsdbench/structure"
	targetNamespace="http://www.codesynthesis.com/xmlns/xsdbench/structure"
	elementFormDefault="qualified">

  <!--
  Strcuture elements:

    - attribute
    - anyAttribute

    - element
    - any

    - all
    - choice
    - sequnce

    - complex type empty content
    - complex type simple content
    - complex type complex content

  Notes:
    - individual tests are sometimes "padded" with other constructs to
      make it more realistic, e.g., almost all tests include both
      attributes and elements.
  -->


  <!--
  attribute

  use = {optional,required}

  Notes:
    - using realistic names instead of 'a', 'b' or 'attr_1', 'attr_2'
  -->
  <complexType name="Attribute">
    <sequence>
      <element name="potato" type="string"/>
      <element name="carrot" type="string" minOccurs="0"/>
      <element name="onion" type="string" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="apple" type="string"/>
    <attribute name="orange" type="string" use="required"/>
    <attribute name="mango" type="string"/>
    <attribute name="grapefruit" type="string" use="required"/>
  </complexType>


  <!--
  element

  min = {0,1}
  max = {1,unbounded}

  Notes:
    - using realistic names instead of 'a', 'b' or 'element_1', 'element_2'
  -->
  <complexType name="Element">
    <sequence>
      <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
      <element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
      <element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="potato" type="string"/>
    <attribute name="carrot" type="string" use="required"/>
  </complexType>



  <!--
  any

  min = {0,1}
  max = {1,unbounded}
  namespace = {##any,##other,##local,##targetNamespace}
  processContents = {skip}

  Notes:
    - there does not appear to be any real-world schemas that use
      processContents value strict.
  -->

  <complexType name="Any">
    <sequence>
      <any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="1"/>
      <element name="apple" type="string"/>
      <any namespace="##local" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
      <element name="orange" type="string"/>
      <any namespace="##targetNamespace" processContents="skip" minOccurs="1" maxOccurs="1"/>
      <element name="mango" type="string"/>
      <any namespace="##any" processContents="skip" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="potato" type="string"/>
    <attribute name="carrot" type="string" use="required"/>
    <anyAttribute namespace="##any" processContents="skip"/>
  </complexType>


  <!--
  all

  min = {0,1}
  max = {1}

  -->
  <complexType name="AllOptional">
    <all minOccurs="0">
      <element name="apple" type="string"/>
      <element name="orange" type="string" minOccurs="0"/>
      <element name="mango" type="string"/>
      <element name="grapefruit" type="string" minOccurs="0"/>
    </all>
  </complexType>

  <complexType name="AllRequired">
    <all>
      <element name="apple" type="string"/>
      <element name="orange" type="string" minOccurs="0"/>
      <element name="mango" type="string"/>
      <element name="grapefruit" type="string" minOccurs="0"/>
    </all>
  </complexType>


  <!--
  choice

  min = {0,1}
  max = {1,unbounded}

  -->

  <complexType name="Choice">
    <sequence>
      <choice minOccurs="0" maxOccurs="1">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </choice>
      <element name="peach" type="string"/> <!-- UPA delimiter -->
      <choice minOccurs="0" maxOccurs="unbounded">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </choice>
      <element name="apricot" type="string"/> <!-- UPA delimiter -->
      <choice minOccurs="1" maxOccurs="1">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </choice>
      <element name="tangerine" type="string"/> <!-- UPA delimiter -->
      <choice minOccurs="1" maxOccurs="unbounded">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </choice>
    </sequence>
  </complexType>


  <!--
  sequence

  min = {0,1}
  max = {1,unbounded}

  -->

  <complexType name="Sequence">
    <sequence>
      <sequence minOccurs="0" maxOccurs="1">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </sequence>
      <element name="peach" type="string"/> <!-- UPA delimiter -->
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </sequence>
      <element name="apricot" type="string"/> <!-- UPA delimiter -->
      <sequence minOccurs="1" maxOccurs="1">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </sequence>
      <element name="tangerine" type="string"/> <!-- UPA delimiter -->
      <sequence minOccurs="1" maxOccurs="unbounded">
        <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
	<element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
	<element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
	<element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
      </sequence>
    </sequence>
  </complexType>


  <!--
  complex type empty content
  -->

  <complexType name="Empty">
    <attribute name="potato" type="string"/>
    <attribute name="carrot" type="string" use="required"/>
  </complexType>

  <complexType name="EmptyExtension">
    <complexContent>
      <extension base="s:Empty">
        <attribute name="onion" type="string"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="EmptyRestriction">
    <complexContent>
      <restriction base="s:EmptyExtension">
        <attribute name="potato" type="string" use="required"/>
	<attribute name="carrot" type="string" use="required"/>
	<attribute name="onion" type="string" use="required"/>
      </restriction>
    </complexContent>
  </complexType>


  <!--
  complex type simple content
  -->

  <complexType name="Simple">
    <simpleContent>
      <extension base="string">
        <attribute name="potato" type="string"/>
        <attribute name="carrot" type="string" use="required"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="SimpleExtension">
    <simpleContent>
      <extension base="s:Simple">
        <attribute name="onion" type="string"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="SimpleRestriction">
    <simpleContent>
      <restriction base="s:SimpleExtension">
        <attribute name="potato" type="string" use="required"/>
        <attribute name="carrot" type="string" use="required"/>
	<attribute name="onion" type="string" use="required"/>
      </restriction>
    </simpleContent>
  </complexType>


  <!--
  complex type complex content
  -->

  <complexType name="Complex">
    <sequence minOccurs="0" maxOccurs="unbounded">
      <element name="apple" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="orange" type="string" minOccurs="0" maxOccurs="unbounded"/>
      <element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
      <element name="grapefruit" type="string" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="potato" type="string"/>
    <attribute name="carrot" type="string" use="required"/>
  </complexType>

  <complexType name="ComplexExtension">
    <complexContent>
      <extension base="s:Complex">
        <choice minOccurs="0" maxOccurs="unbounded">
          <element name="peach" type="string" minOccurs="0" maxOccurs="1"/>
	  <element name="apricot" type="string" minOccurs="0" maxOccurs="unbounded"/>
          <element name="tangerine" type="string" minOccurs="1" maxOccurs="1"/>
	  <element name="banana" type="string" minOccurs="1" maxOccurs="unbounded"/>
        </choice>
	<attribute name="onion" type="string"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="ComplexRestriction">
    <complexContent>
      <restriction base="s:ComplexExtension">
        <sequence>
	  <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="apple" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="orange" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="mango" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="grapefruit" type="string" minOccurs="1" maxOccurs="1"/>
          </sequence>
	  <choice minOccurs="1" maxOccurs="unbounded">
            <element name="peach" type="string" minOccurs="1" maxOccurs="1"/>
	    <element name="apricot" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="tangerine" type="string" minOccurs="1" maxOccurs="1"/>
	    <element name="banana" type="string" minOccurs="1" maxOccurs="1"/>
          </choice>
	</sequence>
	<attribute name="potato" type="string" use="required"/>
	<attribute name="carrot" type="string" use="required"/>
	<attribute name="onion" type="string" use="required"/>
      </restriction>
    </complexContent>
  </complexType>



  <complexType name="Structure">
    <sequence>
      <element name="attribute" type="s:Attribute" maxOccurs="unbounded"/>

      <element name="element" type="s:Element" maxOccurs="unbounded"/>
      <element name="any" type="s:Any" maxOccurs="unbounded"/>

      <element name="all-optional" type="s:AllOptional" maxOccurs="unbounded"/>
      <element name="all-required" type="s:AllRequired" maxOccurs="unbounded"/>
      <element name="choice" type="s:Choice" maxOccurs="unbounded"/>
      <element name="sequence" type="s:Sequence" maxOccurs="unbounded"/>

      <element name="empty" type="s:Empty" maxOccurs="unbounded"/>
      <element name="empty-extension" type="s:EmptyExtension" maxOccurs="unbounded"/>
      <element name="empty-restriction" type="s:EmptyRestriction" maxOccurs="unbounded"/>

      <element name="simple" type="s:Simple" maxOccurs="unbounded"/>
      <element name="simple-extension" type="s:SimpleExtension" maxOccurs="unbounded"/>
      <element name="simple-restriction" type="s:SimpleRestriction" maxOccurs="unbounded"/>

      <element name="complex" type="s:Complex" maxOccurs="unbounded"/>
      <element name="complex-extension" type="s:ComplexExtension" maxOccurs="unbounded"/>
      <element name="complex-restriction" type="s:ComplexRestriction" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="structure" type="s:Structure"/>

</schema>

=== 2m4t/LiCShield/training_session/java_build/SPECjvm2008/resources/xml.validation/structure.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

file      : structure.xml
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : Copyright (c) 2006 Code Synthesis Tools CC
license   : The structure.xml and structure.xsd files are part of the XSDBench W3C XML Schema
            benchmark: http://www.codesynthesis.com/projects/xsdbench/
-->

<s:structure xmlns:s="http://www.codesynthesis.com/xmlns/xsdbench/structure"
             xmlns:o="http://www.codesynthesis.com/xmlns/xsdbench/other"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.codesynthesis.com/xmlns/xsdbench/structure structure.xsd">

 <!-- attribute -->

 <s:attribute orange="orange" grapefruit="grapefruit">
   <s:potato>potato</s:potato>
 </s:attribute>

 <s:attribute mango="mango" orange="orange" grapefruit="grapefruit">
   <s:potato>potato</s:potato>
   <s:carrot>carrot</s:carrot>
   <s:onion>onion</s:onion>
 </s:attribute>

 <s:attribute mango="mango" apple="apple" grapefruit="grapefruit" orange="orange">
   <s:potato>potato</s:potato>
   <s:carrot>carrot</s:carrot>
   <s:onion>onion</s:onion>
   <s:onion>onion</s:onion>
   <s:onion>onion</s:onion>
   <s:onion>onion</s:onion>
   <s:onion>onion</s:onion>
 </s:attribute>

 <!-- element -->

 <s:element carrot="carrot">
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:element>

 <s:element potato="potato" carrot="carrot">
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:element>

 <s:element potato="potato" carrot="carrot">
   <s:apple>apple</s:apple>

   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>

   <s:mango>mango</s:mango>

   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:element>

 <!-- any -->

 <s:any foo="foo" carrot="carrot">
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>

   <!-- ##targetNamespace -->
   <s:apple-target>orange</s:apple-target>

   <s:mango>mango</s:mango>

   <!-- ##any -->
   <s:apple-target>orange</s:apple-target>
 </s:any>

 <s:any potato="potato" foo="foo" bar="bar" carrot="carrot">
   <!-- ##other -->
   <o:apple-other>other</o:apple-other>

   <s:apple>apple</s:apple>

   <!-- ##local -->
   <apple-local>peach</apple-local>
   <apple-local>peach</apple-local>
   <orange-local>orange</orange-local>
   <orange-local>orange</orange-local>
   <mango-local>mango</mango-local>
   <mango-local>mango</mango-local>
   <grapefruit-local>grapefruit</grapefruit-local>
   <grapefruit-local>grapefruit</grapefruit-local>

   <s:orange>orange</s:orange>

   <!-- ##targetNamespace -->
   <s:apple-target>orange</s:apple-target>

   <s:mango>mango</s:mango>

   <!-- ##any -->
   <o:apple-other>other</o:apple-other>
   <apple-local>peach</apple-local>
   <s:apple-target>orange</s:apple-target>
 </s:any>

 <!-- all -->

 <s:all-optional></s:all-optional>

 <s:all-optional>
   <s:apple>apple</s:apple>
   <s:mango>mango</s:mango>
 </s:all-optional>

 <s:all-optional>
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:all-optional>

 <s:all-required>
   <s:apple>apple</s:apple>
   <s:mango>mango</s:mango>
 </s:all-required>

 <s:all-required>
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:all-required>

 <!-- choice -->

 <s:choice>
   <!-- first -->

   <s:peach>peach</s:peach>

   <!-- second -->

   <s:apricot>apricot</s:apricot>

   <!-- third -->
   <s:mango>mango</s:mango>

   <s:tangerine>tangerine</s:tangerine>

   <!-- fourth -->
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:choice>

 <s:choice>
   <!-- first -->
   <s:apple>apple</s:apple>

   <s:peach>peach</s:peach>

   <!-- second -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>

   <s:apricot>apricot</s:apricot>

   <!-- third -->
   <s:mango>mango</s:mango>

   <s:tangerine>tangerine</s:tangerine>

   <!-- fourth -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:choice>

 <!-- sequence -->

 <s:sequence>
   <!-- first -->

   <s:peach>peach</s:peach>

   <!-- second -->

   <s:apricot>apricot</s:apricot>

   <!-- third -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>

   <s:tangerine>tangerine</s:tangerine>

   <!-- fourth -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:sequence>

 <s:sequence>
   <!-- first -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>

   <s:peach>peach</s:peach>

   <!-- second -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>

   <s:apricot>apricot</s:apricot>

   <!-- third -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>

   <s:tangerine>tangerine</s:tangerine>

   <!-- fourth -->
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:apple>apple</s:apple>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:orange>orange</s:orange>
   <s:mango>mango</s:mango>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
   <s:grapefruit>grapefruit</s:grapefruit>
 </s:sequence>

 <!-- empty -->

 <s:empty carrot="carrot"/>
 <s:empty potato="potato" carrot="carrot"/>

 <s:empty-extension carrot="carrot"/>
 <s:empty-extension potato="potato" carrot="carrot"/>
 <s:empty-extension potato="potato" carrot="carrot" onion="onion"/>

 <s:empty-restriction onion="onion" potato="potato" carrot="carrot"/>

 <!-- simple -->

 <s:simple carrot="carrot">simple</s:simple>
 <s:simple potato="potato" carrot="carrot">simple</s:simple>

 <s:simple-extension carrot="carrot">simple</s:simple-extension>
 <s:simple-extension potato="potato" carrot="carrot">simple</s:simple-extension>
 <s:simple-extension potato="potato" carrot="carrot" onion="onion">simple</s:simple-extension>

 <s:simple-restriction onion="onion" potato="potato" carrot="carrot">simple</s:simple-restriction>

 <!-- complex -->
 <s:complex carrot="carrot">
  <s:mango>mango</s:mango>
  <s:grapefruit>grapefruit</s:grapefruit>
 </s:complex>

 <s:complex potato="potato" carrot="carrot">
  <s:apple>apple</s:apple>
  <s:orange>orange</s:orange>
  <s:mango>mango</s:mango>
  <s:grapefruit>grapefruit</s:grapefruit>
 </s:complex>

 <s:complex carrot="carrot" potato="potato">
  <s:apple>apple</s:apple>
  <s:orange>orange</s:orange>
  <s:mango>mango</s:mango>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:apple>apple</s:apple>
  <s:orange>orange</s:orange>
  <s:mango>mango</s:mango>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:apple>apple</s:apple>
  <s:orange>orange</s:orange>
  <s:orange>orange</s:orange>
  <s:orange>orange</s:orange>
  <s:orange>orange</s:orange>
  <s:mango>mango</s:mango>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:grapefruit>grapefruit</s:grapefruit>
 </s:complex>


 <s:complex-extension carrot="carrot">
  <!-- base -->

  <!-- extension -->
  <s:peach>peach</s:peach>
  <s:apricot>apricot</s:apricot>
  <s:apricot>apricot</s:apricot>
  <s:apricot>apricot</s:apricot>
  <s:tangerine>tangerine</s:tangerine>
  <s:banana>banana</s:banana>
  <s:banana>banana</s:banana>
  <s:banana>banana</s:banana>
 </s:complex-extension>

 <s:complex-extension potato="potato" carrot="carrot">
  <!-- base -->
  <s:apple>apple</s:apple>
  <s:orange>orange</s:orange>
  <s:mango>mango</s:mango>
  <s:grapefruit>grapefruit</s:grapefruit>
  <s:apple>apple</s:apple>
  <s:orange>orange</s:orange>
